application: lofty-seer-632
version: 1
runtime: python27
threadsafe: true
api_version: 1
module: api

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: main.API_APPLICATION

# WSGI handler
- url: /.*
  script: main.WSGI_APPLICATION

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: webapp2
  version: latest
